// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: game.sql

package db

import (
	"context"
)

const addNewRpsChoice = `-- name: AddNewRpsChoice :one
INSERT INTO game (player_id, rps_choice)
VALUES ($1, $2) RETURNING id, player_id, rps_choice
`

type AddNewRpsChoiceParams struct {
	PlayerID  int64 `json:"player_id"`
	RpsChoice int32 `json:"rps_choice"`
}

func (q *Queries) AddNewRpsChoice(ctx context.Context, arg AddNewRpsChoiceParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, addNewRpsChoice, arg.PlayerID, arg.RpsChoice)
	var i Game
	err := row.Scan(&i.ID, &i.PlayerID, &i.RpsChoice)
	return i, err
}

const getPlayerChoice = `-- name: GetPlayerChoice :one
SELECT rps_choice 
FROM game 
WHERE MAX (id)
LIMIT 1
`

func (q *Queries) GetPlayerChoice(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getPlayerChoice)
	var rps_choice int32
	err := row.Scan(&rps_choice)
	return rps_choice, err
}
