// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import ()

type Game struct {
	ID        int64 `json:"id"`
	PlayerID  int64 `json:"player_id"`
	RpsChoice int32 `json:"rps_choice"`
}

type Opponent struct {
	ID           int64  `json:"id"`
	OpponentName string `json:"opponent_name"`
	Health       int32  `json:"health"`
}

type Player struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Score    int32  `json:"score"`
	Health   int32  `json:"health"`
	UltMeter int32  `json:"ult_meter"`
}

type Scoreboard struct {
	ID       int64  `json:"id"`
	PlayerID int64  `json:"player_id"`
	Username string `json:"username"`
	Score    int32  `json:"score"`
}
