// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: player.sql

package db

import (
	"context"
)

const getPlayer = `-- name: GetPlayer :one
SELECT id, username, score, health, ult_meter FROM player
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Score,
		&i.Health,
		&i.UltMeter,
	)
	return i, err
}
