// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddNewRpsChoice(ctx context.Context, arg AddNewRpsChoiceParams) (Choice, error)
	AddNewScoreToScoreboard(ctx context.Context, arg AddNewScoreToScoreboardParams) (Scoreboard, error)
	CreatePlayer(ctx context.Context, username string) (Player, error)
	GetPlayer(ctx context.Context, username string) (Player, error)
	GetPlayerById(ctx context.Context) (interface{}, error)
	GetPlayerChoice(ctx context.Context, playerID int64) (int32, error)
	GetPlayerHealth(ctx context.Context, id int64) (int32, error)
	GetPlayerScore(ctx context.Context, id int64) (int32, error)
	GetPlayersUlt(ctx context.Context, id int64) (int32, error)
	GetUsername(ctx context.Context, id int64) (string, error)
	ListHigestScores(ctx context.Context) ([]ListHigestScoresRow, error)
	UpdatePlayerHealth(ctx context.Context, arg UpdatePlayerHealthParams) (Player, error)
	UpdatePlayerName(ctx context.Context, arg UpdatePlayerNameParams) (Player, error)
	UpdatePlayersUlt(ctx context.Context, arg UpdatePlayersUltParams) (Player, error)
	UpdateScore(ctx context.Context, id int64) (Player, error)
}

var _ Querier = (*Queries)(nil)
