// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: scoreboard.sql

package db

import (
	"context"
)

const addNewScoreToScoreboard = `-- name: AddNewScoreToScoreboard :one
INSERT INTO scoreboard (player_id, username, score)
VALUES ($1, $2, $3) 
RETURNING id, player_id, username, score
`

type AddNewScoreToScoreboardParams struct {
	PlayerID int64  `json:"player_id"`
	Username string `json:"username"`
	Score    int32  `json:"score"`
}

func (q *Queries) AddNewScoreToScoreboard(ctx context.Context, arg AddNewScoreToScoreboardParams) (Scoreboard, error) {
	row := q.db.QueryRowContext(ctx, addNewScoreToScoreboard, arg.PlayerID, arg.Username, arg.Score)
	var i Scoreboard
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Username,
		&i.Score,
	)
	return i, err
}
